### ISSUE TITLE
Sending Requirement Object

### ISSUE THREAD

**Issue by rahafrouz** [smartfog/fogflow#24]
Hi,

I think it might be a good idea to put a sample `Requirement` object in the docs. I have set up the Fogflow on one server and another worker (broker, worker) on another VM. The setup is fine and two brokers are visible in the `System Management` of the designer.

I try to send a `requirement` to the broker to start the flow. This is the requirement object I send:

```
POST http://MY_BROKER_IN_THE_CLOUD:8080/ngsi10/updateContext
BODY:
{
	"contextElements":[
           {
                "entityId": {
                    "id": "Requirement.LTU",
                    "type": "Requirement",
                    "isPattern": false
                }, 
                "attributes":[{
                	"output":   {"type":"string", "value":"Stat"},
                	"scheduler":{"type":"string", "value":"closest_first"}
                }],
                "metadata":{
                	"topology":{"type":"string", "value":"anomaly-detection"}
                }

            }
		],
	"updateAction": "UPDATE"
}
```

however, on the logs I see that the attributes are not transmitted properly. see the log:
```
broker_1        | DEBUG: 2019/03/01 08:20:58 utils.go:41: {"subscriptionId":"31750544-afbc-47cd-b6d7-4d180aff7924","originator":"","contextResponses":[{"contextElement":{"entityId":{"id":"Requirement.LTU","type":"Requirement"},"attributes":[{"name":"","contextValue":null}]},"statusCode":{"code":200,"reasonPhrase":"OK"}}]}
```
Seems some problem with getting attributes. That leads to a panic in the `master` as well:

```
master_1        | DEBUG: 2019/03/01 08:20:58 master.go:212: NGSI10 NOTIFY  31750544-afbc-47cd-b6d7-4d180aff7924  ,  Requirement
master_1        | INFO: 2019/03/01 08:20:58 =================handle requirement update=================
master_1        | INFO: 2019/03/01 08:20:58 read the requirement entity
master_1        | interface conversion: interface {} is nil, not string
master_1        | goroutine 982 [running]:
master_1        | runtime/debug.Stack(0xc000239800, 0x777600, 0xc000068f30)
master_1        | 	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/debug/stack.go:24 +0xa7
master_1        | github.com/ant0ine/go-json-rest/rest.(*RecoverMiddleware).MiddlewareFunc.func1.1(0xab0eb0, 0x842800, 0xc000068e70)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/recover.go:41 +0x6e
master_1        | panic(0x777600, 0xc000068f30)
master_1        | 	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
master_1        | main.(*TopologyMgr).handleRequirementUpdate(0xc00001e870, 0xc000186000, 0x1, 0x4, 0xc000092180, 0x24)
master_1        | 	/Users/cheng/work/go/src/github.com/smartfog/fogflow/master/topologyMgr.go:95 +0x7f7
master_1        | main.(*Master).onReceiveContextNotify(0xc000073ba0, 0xc00009c140)
master_1        | 	/Users/cheng/work/go/src/github.com/smartfog/fogflow/master/master.go:222 +0x34e
master_1        | main.(*Master).onReceiveContextNotify-fm(0xc00009c140)
master_1        | 	/Users/cheng/work/go/src/github.com/smartfog/fogflow/master/master.go:97 +0x34
master_1        | github.com/smartfog/fogflow/common/ngsi.(*NGSIAgent).handleNotifyContext(0xc00000a980, 0x842800, 0xc000068e70, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/smartfog/fogflow/common/ngsi/ngsiagent.go:51 +0x171
master_1        | github.com/smartfog/fogflow/common/ngsi.(*NGSIAgent).handleNotifyContext-fm(0x842800, 0xc000068e70, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/smartfog/fogflow/common/ngsi/ngsiagent.go:24 +0x48
master_1        | github.com/ant0ine/go-json-rest/rest.(*router).AppFunc.func1(0x842800, 0xc000068e70, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/router.go:56 +0x9f
master_1        | github.com/ant0ine/go-json-rest/rest.(*RecoverMiddleware).MiddlewareFunc.func1(0x842800, 0xc000068e70, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/recover.go:57 +0x8a
master_1        | github.com/ant0ine/go-json-rest/rest.(*PoweredByMiddleware).MiddlewareFunc.func1(0x842800, 0xc000068e70, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/powered_by.go:26 +0xae
master_1        | github.com/ant0ine/go-json-rest/rest.(*RecorderMiddleware).MiddlewareFunc.func1(0x842840, 0xc00000a0c0, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/recorder.go:22 +0x9a
master_1        | github.com/ant0ine/go-json-rest/rest.(*TimerMiddleware).MiddlewareFunc.func1(0x842840, 0xc00000a0c0, 0xc00000a0a0)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/timer.go:20 +0xfc
master_1        | github.com/ant0ine/go-json-rest/rest.adapterFunc.func1(0x842300, 0xc0000fe380, 0xc00013c400)
master_1        | 	/Users/cheng/work/go/src/github.com/ant0ine/go-json-rest/rest/middleware.go:70 +0xd7
master_1        | net/http.HandlerFunc.ServeHTTP(0xc00001c960, 0x842300, 0xc0000fe380, 0xc00013c400)
master_1        | 	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1964 +0x44
master_1        | net/http.serverHandler.ServeHTTP(0xc00016f860, 0x842300, 0xc0000fe380, 0xc00013c400)
master_1        | 	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2741 +0xab
master_1        | net/http.(*conn).serve(0xc000084b40, 0x842580, 0xc0000560c0)
master_1        | 	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1847 +0x646
master_1        | created by net/http.(*Server).Serve
master_1        | 	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2851 +0x2f5
```
I think it is a good idea that `master` validate the objects before using them. 
My speculation is that there is some problem with my `Requirement`. What do you think?

**Comment by smartfog** [comment]
In deed, this is a problem. I did not realize it since the tutorial use the javascript library to send the requirement object. However, if you want to send the raw NGSI update, you need to convert the object to NGSI element. 

function JSONObject2CtxElement(ob) {
    console.log('convert json object to context element') 
    var contextElement = {};
    
    contextElement.entityId = ob.entityId;
    
    contextElement.attributes = [];
    if(ob.attributes) {
        for( key in ob.attributes ) {
            attr = ob.attributes[key];
            contextElement.attributes.push({name: key, type: attr.type, contextValue: attr.value});
        }
    }
    
    contextElement.domainMetadata = [];
    if(ob.metadata) {
        for( key in ob.metadata ) {
            meta = ob.metadata[key];
            contextElement.domainMetadata.push({name: key, type: meta.type, value: meta.value});
        }
    }    

    return contextElement;
}  

I will update the tutorial with a raw NGSI update to send the requirement. to be done next week. Thanks for your suggestion. for the time being, please refer to the format in the following example. 

{
   "entityId":{
      "id":"Requirement.001",
      "type":"Requirement",
      "isPattern":false
   },
   "attributes":[
      {
         "name":"output",
         "type":"string",
         "contextValue":"Stat"
      },
      {
         "name":"scheduler",
         "type":"string",
         "contextValue":"closest_first"
      }
   ],
   "domainMetadata":[
      {
         "name":"topology",
         "type":"string",
         "value":"anomaly"
      }
   ]
}

Hopefully, this can help you.
