### ISSUE TITLE
error to communicate with rabbitmq Channel: Exception (504) Reason: "channel/connection is not open"

### ISSUE THREAD

**Issue by YujiAzama** [smartfog/fogflow#32]
I trying to test the multi-node FogFlow environment. I built a Cloud Node, two Edge Nodes, and three PowerPanel devices.
But worker container in the Edge Node1 stopped in about a minute.

```
$ docker ps -a
CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS                     PORTS                    NAMES                                                                                                  
8d784c698380        fogflow/worker:arm   "/worker"           5 minutes ago       Exited (2) 4 minutes ago                            edgeworker                                                                                             
e98b3fdf2fac        fogflow/broker:arm   "/broker"           5 minutes ago       Up 5 minutes               0.0.0.0:8080->8080/tcp   edgebroker                                                                                             
```

And it output the following error.

```
$ docker logs edgeworker
INFO: 2019/07/11 04:31:56 annouce myself to the nearby broker                                                         

2019/07/11 04:31:58 [*] Waiting for messages. To exit press CTRL+C                                                    
Going to retry launching the edge node. Error: Received an empty message.error to communicate with rabbitmq Channel: Exception (504) Reason: "channel/connection is not open"                                                               
                                                                                                                      
panic: runtime error: invalid memory address or nil pointer dereference                                               
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x2f8dc0]                                               
                                                                                                                      
goroutine 35 [running]:                                                                                               
github.com/streadway/amqp.(*Channel).Close(0x0, 0x0, 0x0)                                                             
        /Users/cheng/work/go/src/github.com/streadway/amqp/channel.go:426 +0x24                                       
github.com/smartfog/fogflow/common/communicator.(*Communicator).Publish(0xfcc280, 0x103e000, 0x445e38, 0xc5e078)      
        /Users/cheng/work/go/src/github.com/smartfog/fogflow/common/communicator/communicator.go:134 +0x2a4           
main.(*Worker).heartbeat(0xc9a580)                                                                                    
        /Users/cheng/work/go/src/github.com/smartfog/fogflow/worker/worker.go:210 +0xb8                               
main.(*Worker).onTimer(0xc9a580)                                                                                      
        /Users/cheng/work/go/src/github.com/smartfog/fogflow/worker/worker.go:205 +0x1c                               
main.(*Worker).Start.func2(0xc9a580)                                                                                  
        /Users/cheng/work/go/src/github.com/smartfog/fogflow/worker/worker.go:111 +0x38                               
created by main.(*Worker).Start                                                                                       
        /Users/cheng/work/go/src/github.com/smartfog/fogflow/worker/worker.go:108 +0x5cc                              
```

The other worker is working fine.
This error seems to be a connection error with RabbitMQ, RabbitMQ is working fine.

The configuration of Edge Node1 is below.
```
{                                       
    "coreservice_ip": "192.168.28.10",  
    "external_hostip": "192.168.28.230",
    "internal_hostip": "172.17.0.1",    
    "physical_location":{               
        "longitude": 127.6784711,       
        "latitude": 26.2157166,         
        "section": "01",                
        "district": "02",               
        "city": "Naha"                  
    },                                  
    "logical_location": {               
        "node_no": 1,                   
        "site_no": 2,                   
        "layer_no": 2,                  
        "parent_site_no": 1             
    },                                  
    "logging":{                         
        "info":"stdout",                
        "error":"stderr",               
            "protocol": "stdout",       
            "debug": "stdout"           
    },                                  
    "discovery": {                      
        "port": 443                     
    },                                  
    "broker": {                         
        "port": 8080,                   
        "websocket": 8090               
    },                                  
    "worker": {                         
        "container_autoremove": false   
    },                                  
    "rabbitmq": {                       
        "port": 5672,                   
        "username": "admin",
        "password":"mypass"
    }
}
```

The configuration of Edge Node2 is below.
```
{
    "coreservice_ip": "192.168.28.10",
    "external_hostip": "192.168.28.231",
    "internal_hostip": "172.17.0.1",
    "physical_location":{
        "longitude": 127.6903532,
        "latitude": 26.2422305,
        "section": "02",
        "district": "03",
        "city": "Urasoe"
    },
    "logical_location": {
        "node_no": 2,
        "site_no": 3,
        "layer_no": 2,
        "parent_site_no": 1
    },
    "logging":{
        "info":"stdout",
        "error":"stderr",
            "protocol": "stdout",
            "debug": "stdout"
    },
    "discovery": {
        "port": 443
    },
    "broker": {
        "port": 8080,
        "websocket": 8090
    },
    "worker": {
        "container_autoremove": false
    },
    "rabbitmq": {
        "port": 5672,
        "username": "admin",
        "password":"mypass"
    }
}
```

If this is a known issue, Is there a solution?

**Comment by YujiAzama** [comment]
This issue was solved by rebuilding the Edge Node.
