### ISSUE TITLE
Designer getting error, if Intent ID and Fogfunction name is incorrect for DELETE API. 

### ISSUE THREAD

**Issue by vrawatnec** [smartfog/fogflow#380]
Delete Intent and Fogfunction API is getting errors.
1. DELETE Intent API giving error when Id is wrong.  Error log as below-

```
file:///home/ubuntu/Documents/fogflow_proj/src/fogflow/designer/main.js:419
    serviceintent.action = 'DELETE';
                         ^
TypeError: Cannot set properties of undefined (setting 'action')
    at file:///home/ubuntu/Documents/fogflow_proj/src/fogflow/designer/main.js:419:26
```

2. DELETE Fogfunction API giving error when Fogfunction name does not exist.  Error log as below-

```
file:///home/ubuntu/Documents/fogflow_proj/src/fogflow/designer/main.js:467
    var serviceintent = fogfunction.intent
                                    ^
TypeError: Cannot read properties of undefined (reading 'intent')
    at file:///home/ubuntu/Documents/fogflow_proj/src/fogflow/designer/main.js:467:37

```

**Comment by naveennec** [comment]
Closing this issue as Below PR is merged in development branch.
https://github.com/smartfog/fogflow/pull/381

**Comment by naveennec** [comment]
Closing this issue as Below PR is merged in development branch.
https://github.com/smartfog/fogflow/pull/381
